# .github/workflows/ci.yml

name: Integracion Continua
  
on:
  push:
    branches:
      - main
      - Dev
      - QA
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Usar un runner de Windows si estás construyendo proyectos de .NET Framework

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.8.x'  # Ajusta la versión según tus necesidades

    - name: Install msbuild
      shell: powershell
      run: |
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Install-Module -Name VSSetup -Force -AllowClobber
        Install-VisualStudio -Channel 17.0 -Product Microsoft.VisualStudio.Product.Enterprise

    - name: Build
      run: msbuild -p:Configuration=Release

    - name: Test
      run: dotnet test --configuration Release --no-restore --logger "trx;LogFileName=test_results.trx"
        
