# .github/workflows/ci.yml

name: Integracion Continua

on:
  push:
    branches:
      - main
      - Dev
      - QA
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Install NuGet
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run tests with dotnet
        run: dotnet test --logger trx --results-directory TestResults

