# .github/workflows/ci.yml

name: Integracion Continua
  
on:
  push:
    branches:
      - main
      - Dev
      - QA
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Usar un runner de Windows si estás construyendo proyectos de .NET Framework

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build with MSBuild
      run: msbuild ProyectoBiblioteca/ProyectoBiblioteca.sln /p:Configuration=Release

    - name: Test with VSTest
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" ProyectoBiblioteca.Tests\bin\Release\net48\ProyectoBiblioteca.Tests.dll /logger:trx
    
