# .github/workflows/ci.yml

name: Integracion Continua
  
on:
  push:
    branches:
      - main
      - Dev
      - QA
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Framework SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.8'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test --configuration Release --logger trx --results-directory ./TestResults
        continue-on-error: true

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: ./TestResults

