# .github/workflows/ci.yml

name: Integracion Continua
  
on:
  push:
    branches:
      - main
      - Dev
      - QA
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and test
      run: |
        dotnet build --configuration Release --no-restore
        dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: '**/test_results.trx'


