# .github/workflows/ci.yml

name: Integracion Continua
  
on:
  push:
    branches:
      - main
      - Dev
      - QA
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore Proyecto.sln

      - name: Build with MSBuild
        run: msbuild Proyecto.sln /p:Configuration=Release

      - name: Test with VSTest
        run: |
          dotnet test ProyectoBiblioteca.Tests/ProyectoBiblioteca.Tests.csproj --logger trx
        working-directory: ${{ github.workspace }}

